### PR TITLE
Changed colour of current tab

### PR DESCRIPTION
**Pull request by idottertcrosser**
Changed rgb of current tab to 245,246,247 so that it matches tool bar as this looks nicer (IMO).

### CODE REVIEW

**Comment by wilfredwee** [comment]
Hey there, thanks so much for the PR!

The problem I'm facing with just editing the current tab color is that OSX and Windows have different colors for their toolbar, and I can't use variables for the color inside the svg.

I'm investigating a way to detect the OS in the CSS and apply the correct CSS accordingly. Will look into this in the weekend. :)

**Comment by idottertcrosser** [comment]
Oh I see.  I'll remove my pull request.

**Comment by wilfredwee** [comment]
Hey there, I've hopefully fixed the problem in this commit: 389c751f6f6a6d93a9398b5886cf3372fff17a72

I'll close this PR but feel free to re-open it if there's anything else you'd like to discuss! :)

**Comment by wilfredwee** [comment]
Related release: https://github.com/wilfredwee/photon-australis/tree/v0.3.1

**Pull request closed without merging**
